name: flutter_generator_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: ^2.0.0
executables:
  flutter_gen: 
  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
